### ISSUE TITLE
Where to talk about your fork sfml opengl es 2

### ISSUE THREAD

**Issue by Nathan-M-code** [Zombieschannel/winsfmlandroid#1]
Hey, sorry to post an issue on that repository, but I can't make one from the fork page.
I am using your Opengl es 2 fork of SFML. It is really great for me, since the sfml team will probably implement it in a long time.
Where can I write you about the problems I encountered ? Discord or any social media, maybe just here.
Thank you

**Comment by Zombieschannel** [comment]
I just enabled issues on the Zombieschannel/SFML repo, it seems like it was disabled by default, so hopefully you should be able to see it now. 😄
